#pragma once
#include <iostream>
#include <ctime>
#include <chrono>
#include <thread>
#include <iomanip>
#include <sys/types.h>
#include <sys/socket.h>
#include <netinet/in.h>
#include <unistd.h>
#include <curl/curl.h>
#include "json.hpp"